
compiler:
  - gcc
  - clang

language: c

os:
  - linux
  - osx

addons:
  apt:
    sources:
       - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - clang
      - g++-6
      - gcc-6
      - libusb-1.0.0-dev

script:
  - git fetch --tags
  - printenv
  - cmake --version
  - ./.travis.sh
